#!/bin/bash
#
# https://raw.githubusercontent.com/dayne/d.pi/main/bootstrap

sudo apt update && sudo apt install git curl

curl -fsSL https://get.docker.com -o get-docker.sh

sudo sh get-docker.sh

sudo usermod -aG docker pi


